spring:
  application:
    name: data-exchange-client
  jackson:
    serialization:
      write_dates_as_timestamps: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    elasticsearch:
      enabled: false
